apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etcd
resources:
- ../../settings
- etcd.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
replacements:
- source: {fieldPath: data.cluster.etcd.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: etcd}
    fieldPaths: [spec.clusterIP]
- source: {fieldPath: data.cluster.etcd.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: etcd}
    fieldPaths: [spec.clusterIPs.0]
- source: {fieldPath: data.cluster.etcd.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: etcd}
    fieldPaths: [spec.clusterIPs.1]
