apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node
resources:
- image-registry.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/nginx.conf
  name: image-registry-config
generatorOptions:
  disableNameSuffixHash: true
