apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: home-cluster
provisioner: nfs.csi.k8s.io
parameters:
  server: nfsShares.homeCluster.addr
  share: nfsShares.homeCluster.path
  subDir: "."
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: [hard, nfsvers=4.1]
