apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../cluster-vars
- pool.yaml
- bgpp.yaml
- Kptfile
- resourcegroup.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata: {name: cluster-vars, annotations: {config.kubernetes.io/local-config: "true"}}
replacements:
- source: {fieldPath: data.CLUSTER_IPV4_LB_CIDR, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {group: cilium.io, kind: CiliumLoadBalancerIPPool, name: lan-addresses}
    fieldPaths: [spec.blocks.0.cidr]
- source: {fieldPath: data.CLUSTER_IPV6_LB_CIDR, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {group: cilium.io, kind: CiliumLoadBalancerIPPool, name: lan-addresses}
    fieldPaths: [spec.blocks.1.cidr]
- source: {fieldPath: data.ROUTER_IPV4, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {group: cilium.io, kind: CiliumBGPPeeringPolicy, name: router}
    fieldPaths: [spec.virtualRouters.0.neighbors.0.peerAddress]
    options: {delimiter: '/', index: 0}
- source: {fieldPath: data.ROUTER_IPV6, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {group: cilium.io, kind: CiliumBGPPeeringPolicy, name: router}
    fieldPaths: [spec.virtualRouters.0.neighbors.1.peerAddress]
    options: {delimiter: '/', index: 0}
