apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../settings/replacements
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/deploy/longhorn.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/backing-image-data-source-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/backing-image-manager-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/instance-manager-networking.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/manager-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/recovery-backend-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/webhook-network-policy.yaml
- ui.yaml
- rwx-storage.yaml
- snapshot.yaml
- networkpolicies.yaml
- Kptfile
- resourcegroup.yaml
patches:
- path: longhorn.yaml
replacements:
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: longhorn}
    fieldPaths: [spec.tls.0.hosts.0]
    options: {delimiter: ., index: 1}
  - select: {group: networking.k8s.io, kind: Ingress, name: longhorn}
    fieldPaths: [spec.rules.0.host]
    options: {delimiter: ., index: 1}
- source: {fieldPath: data.cluster.acmeProvider.group, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: longhorn}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-group]
- source: {fieldPath: data.cluster.acmeProvider.kind, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: longhorn}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-kind]
- source: {fieldPath: data.cluster.acmeProvider.issuer, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: longhorn}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer]
