---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: longhorn
    - matchExpressions:
      - key: longhorn.io/job-task
        operator: Exists
    - matchExpressions:
      - key: recurring-job.longhorn.io
        operator: Exists
    - matchExpressions:
      - key: longhorn.io/component
        operator: Exists
    - matchExpressions:
      - key: app
        operator: In
        values: [csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter]
  - fromEntities:
    - host
    - remote-node
  egress:
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: longhorn
    - matchExpressions:
      - key: longhorn.io/job-task
        operator: Exists
    - matchExpressions:
      - key: recurring-job.longhorn.io
        operator: Exists
    - matchExpressions:
      - key: longhorn.io/component
        operator: Exists
    - matchExpressions:
      - key: app
        operator: In
        values: [csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter]
  - toEntities:
    - kube-apiserver
