apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pxe
resources:
- ../../settings/manifests
- ../../mounts/manifests
- tftpd.yaml
- nbd-server.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
replacements:
- source: {fieldPath: data.machines.k8sMaster.hostname, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: tftpd}
    fieldPaths: [spec.template.spec.nodeSelector.kubernetes\.io/hostname]
