---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tftpd
  labels:
    app.kubernetes.io/name: pxe
    app.kubernetes.io/component: tftpd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pxe
      app.kubernetes.io/component: tftpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pxe
        app.kubernetes.io/component: tftpd
    spec:
      nodeSelector:
        kubernetes.io/hostname: machines.k8sMaster.hostname
      hostNetwork: true
      containers:
      - name: tftpd
        image: distribution.docker-registry.svc.cluster.local/tftpd:latest
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
            add:
            - NET_BIND_SERVICE
            - SETUID
            - SETGID
            - SYS_CHROOT
        ports:
        - name: tftp
          port: 69
        volumeMounts:
        - name: tftp
          mountPath: /var/lib/tftp
          readOnly: true
      volumes:
      - name: images
        nfs:
          server: nfsShares.images.addr
          path: nfsShares.images.path
          readOnly: true
