---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftpd
  labels:
    app.kubernetes.io/name: pxe
    app.kubernetes.io/component: tftpd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pxe
      app.kubernetes.io/component: tftpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pxe
        app.kubernetes.io/component: tftpd
    spec:
      nodeSelector:
        kubernetes.io/hostname: machines.k8sMaster.hostname
      hostNetwork: true
      containers:
      - name: tftpd
        image: distribution.docker-registry.svc.cluster.local/tftpd:latest
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
            add:
            - NET_BIND_SERVICE
            - SETUID
            - SETGID
            - SYS_CHROOT
        ports:
        - name: tftp
          containerPort: 69
          hostPort: 69
        volumeMounts:
        - name: home-cluster
          mountPath: /var/lib/home-cluster
        - name: home-cluster
          mountPath: /tftp/cluster.ipxe
          subPath: workloads/pxe/config/cluster.ipxe
        - name: images
          mountPath: /tftp/kernels
          subPath: kernels
          readOnly: true
      volumes:
      - name: home-cluster
        nfs:
          server: nfsShares.homeCluster.addr
          path: nfsShares.homeCluster.path
          readOnly: true
      - name: images
        nfs:
          server: nfsShares.images.addr
          path: nfsShares.images.path
          readOnly: true
