apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
- networkpolicy.yaml
- letsencrypt.yaml
- selfsigned.yaml
- Kptfile
- resourcegroup.yaml
patches:
- path: overrides.yaml
