---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: step-issuer-approver-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: step-issuer-approver-role
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: step-issuer-approver-role
  labels:
    app.kubernetes.io/name: step-ca
    app.kubernetes.io/component: issuer
rules:
- apiGroups: [cert-manager.io]
  resourceNames: [stepissuers.certmanager.step.sm/*, stepclusterissuers.certmanager.step.sm/*]
  resources: [signers]
  verbs: [approve]
