---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-secret-generator
spec:
  template:
    metadata:
      labels:
        cluster.local/allow-apiserver-egress: "true"
    spec:
      containers:
      - name: kubernetes-secret-generator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            $patch: delete
          value: ""
