apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docker-registry
resources:
- ../settings
- auth.yaml
- distribution.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - auth_config.yml=config/auth.yaml
  name: auth-config
- files:
  - config/scripts/auth.sh
  - config/scripts/init-docker-auth.sh
  name: auth-scripts
- files:
  - config.yml=config/distribution.yaml
  name: distribution
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: distribution}
    fieldPaths: [spec.tls.0.hosts.0]
    options: {delimiter: '.', index: 1}
  - select: {group: networking.k8s.io, kind: Ingress, name: distribution}
    fieldPaths: [spec.rules.0.host]
    options: {delimiter: '.', index: 1}
  - select: {group: networking.k8s.io, kind: Ingress, name: docker-auth}
    fieldPaths: [spec.tls.0.hosts.0]
    options: {delimiter: '.', index: 1}
  - select: {group: networking.k8s.io, kind: Ingress, name: docker-auth}
    fieldPaths: [spec.rules.0.host]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: StatefulSet, name: distribution}
    fieldPaths: ["spec.template.spec.containers.[name=distribution].env.[name=DOMAIN].value"]
    options: {delimiter: '.', index: 1}
- source: {fieldPath: data.cluster.acmeProvider.group, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: distribution}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-group]
  - select: {group: networking.k8s.io, kind: Ingress, name: docker-auth}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-group]
- source: {fieldPath: data.cluster.acmeProvider.kind, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: distribution}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-kind]
  - select: {group: networking.k8s.io, kind: Ingress, name: docker-auth}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-kind]
- source: {fieldPath: data.cluster.acmeProvider.issuer, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: distribution}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer]
  - select: {group: networking.k8s.io, kind: Ingress, name: docker-auth}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer]
