---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phxc:cilium-ready-checks
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: node
rules:
- apiGroups: [cilium.io]
  resources: [ciliumloadbalancerippools, ciliumclusterwidenetworkpolicies]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: phxc::node:cilium-ready-checks
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: node
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: phxc:cilium-ready-checks
  apiGroup: rbac.authorization.k8s.io
