apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- ../../settings
- coredns.yaml
replacements:
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=DOMAIN].value"]
- source: {fieldPath: data.cluster.wanIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=WAN_IPV4].value"]
- source: {fieldPath: data.machines.k8sMaster.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=K8SMASTER_IPV4].value"]
- source: {fieldPath: data.machines.k8sMaster.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=K8SMASTER_IPV6].value"]
- source: {fieldPath: data.cluster.etcd.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=ETCD_IPV4].value"]
- source: {fieldPath: data.cluster.etcd.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=ETCD_IPV6].value"]
- source: {fieldPath: data.nfsShares.homeCluster.addr, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps}
    fieldPaths: ["spec.template.spec.volumes.[name=custom-config-volume].nfs.server"]
- source: {fieldPath: data.nfsShares.homeCluster.path, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps}
    fieldPaths: ["spec.template.spec.volumes.[name=custom-config-volume].nfs.path"]
    options: {delimiter: /, index: 0}
