apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-kube-config
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: refresh-kube-config
spec:
  schedule: "00 05 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: smallstep
            app.kubernetes.io/component: refresh-kube-config
            cluster.local/allow-internet-egress: "true"
        spec:
          nodeSelector:
            kubernetes.io/hostname: machines.k8sMaster.hostname
          restartPolicy: Never
          containers:
          - name: refresh-kube-config
            image: distribution.docker-registry.svc.cluster.local/step-ca-bootstrap:latest
            imagePullPolicy: Always
            command: [/var/lib/home-cluster/workloads/smallstep/commands/create-kube-config.sh]
            args: ['system:admin', 'system:masters']
            securityContext:
              readOnlyRootFilesystem: true
            volumeMounts:
            - name: home-cluster
              mountPath: /var/lib/home-cluster
            - name: certs
              mountPath: /home/step/certs
            - name: kube-apiserver-client-ca-cert
              mountPath: /home/step/certs/kube_apiserver_client_ca.crt
              readOnly: true
            - name: kube-apiserver-client-ca-key
              mountPath: /home/step/certs/kube_apiserver_client_ca_key
              readOnly: true
            - name: persistent-certs
              mountPath: /home/step/persistent-certs
          volumes:
          - name: home-cluster
            nfs:
              server: nfsShares.homeCluster.addr
              path: nfsShares.homeCluster.path
              readOnly: true
          - name: kube-apiserver-client-ca-cert
            hostPath:
              path: /var/lib/persistent/lib-rancher/k3s/server/tls/client-ca.crt
              type: File
          - name: kube-apiserver-client-ca-key
            hostPath:
              path: /var/lib/persistent/lib-rancher/k3s/server/tls/client-ca.key
              type: File
          - name: certs
            emptyDir:
              medium: Memory
          - name: persistent-certs
            persistentVolumeClaim:
              claimName: step-ca-certs
