server:
  addr: ":5001"
token:
  issuer: Docker registry auth server
  expiration: 900
  certificate: /config/certs/tls.crt
  key: /config/certs/tls.key
# Create passwords with:
# PASSWORD=$(randpass -l 32); HASH=$(htpasswd -nbB "" "$PASSWORD"); printf "%s\n%s\n" "${HASH/#:/}" "$PASSWORD"; unset HASH PASSWORD
users:
  $K3S_USERNAME:
    password: $K3S_PASSWORD
acl:
- match:
    account: /.*/
  actions: [pull]
  comment: Everybody can pull
- match:
    account: system/admin
  actions: ["*"]
  comment: Admin can do everything
ext_auth:
  command: /var/lib/home-cluster/lib/container-commands/docker-registry/auth.sh
