server:
  addr: ":5001"
token:
  issuer: Docker registry auth server
  expiration: 900
  certificate: /config/certs/jwt/tls.crt
  key: /config/certs/jwt/tls.key
# Create passwords with:
# PASSWORD=$(randpass -l 32); HASH=$(htpasswd -nbB "" "$PASSWORD"); printf "%s\n%s\n" "${HASH/#:/}" "$PASSWORD"; unset HASH PASSWORD
users:
  $K3S_USERNAME:
    password: "$K3S_PASSWORD"
  $KANIKO_USERNAME:
    password: "$KANIKO_PASSWORD"
acl:
- match:
    account: $K3S_USERNAME
  actions: [pull]
  comment: $K3S_USERNAME can pull
- match:
    account: $KANIKO_USERNAME
  actions: [pull, push]
  comment: $KANIKO_USERNAME can pull & push
- match:
    account: system/admin
  actions: ["*"]
  comment: Admin can do everything
ext_auth:
  command: /var/lib/home-cluster/lib/container-commands/docker-registry/auth.sh
