---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phxc:basic-ready-checks
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: node
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, list]
- apiGroups: [""]
  resources: [namespaces, endpoints]
  verbs: [get, list]
- apiGroups: [apps]
  resources: [deployments, statefulsets]
  verbs: [get, list]
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: phxc:node:basic-ready-checks
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: node
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: phxc:basic-ready-checks
  apiGroup: rbac.authorization.k8s.io
