apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pxe
resources:
- ../../settings/replacements
- ../../settings/node-settings
- ../../mounts/manifests
- tftpd.yaml
- boot-server.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/boot-server.conf
  name: nginx
replacements:
- source: {fieldPath: data.cluster.bootServer.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: boot-server}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.bootServer.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: boot-server}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
