apiVersion: batch/v1
kind: Job
metadata:
  name: build-boot-server
  labels:
    app.kubernetes.io/name: bootstrap
    app.kubernetes.io/component: boot-server
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bootstrap
        app.kubernetes.io/component: boot-server
        cluster.local/allow-internet-egress: "true"
    spec:
      restartPolicy: Never
      initContainers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --dockerfile=context/Dockerfile
        - --destination=cluster.local/boot-server:latest
        - --tar-path=/workspace/images/boot-server:latest.tar.tmp
        - --no-push
        env:
        - name: GGCR_EXPERIMENT_ESTARGZ
          value: "1"
        volumeMounts:
        - name: context
          mountPath: /workspace/context
        - name: common-context
          mountPath: /workspace/common-context
        - name: images
          mountPath: /workspace/images
      containers:
      - name: move-image
        image: busybox
        args: [mv, /images/boot-server:latest.tar.tmp, /images/boot-server:latest.tar]
        volumeMounts:
        - name: images
          mountPath: /images
      volumes:
      - name: context
        configMap:
          name: boot-server
      - name: common-context
        configMap:
          name: common-context
          defaultMode: 0755
      - name: images
        hostPath:
          path: /var/lib/phoenix-cluster/container-images
          type: DirectoryOrCreate
