apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smallstep
resources:
- ../settings
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- bootstrap.yaml
- certificates.yaml
- kube-apiserver-client-ca.yaml
- issuer.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/bootstrap.sh
  name: step-ca-bootstrap
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - config/setup-step-ca-config.sh
  name: setup-step-ca-config
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - config/ca.json
  name: step-ca-config
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - config/templates/kube-apiserver-client-cert.tpl
  name: step-ca-templates
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - config/setup-kube-apiserver-client-ca-config.sh
  name: setup-kube-apiserver-client-ca-config
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - ca.json=config/kube-apiserver-client-ca.json
  name: kube-apiserver-client-ca-config
  options:
    labels:
      app.kubernetes.io/name: smallstep
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.cluster.pkiName, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job, name: step-ca-bootstrap}
    fieldPaths: ["spec.template.spec.containers.[name=step-ca-bootstrap].env.[name=PKI_NAME].value"]
- source: {fieldPath: data.machines.k8sMaster.hostname, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job, name: step-ca-bootstrap}
    fieldPaths: ["spec.template.spec.containers.[name=step-ca-bootstrap].env.[name=K8S_API_HOST].value"]
- source: {fieldPath: data.admin.uid, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job, name: step-ca-bootstrap}
    fieldPaths: ["spec.template.spec.containers.[name=step-ca-bootstrap].env.[name=KUBE_CONFIG_OWNER].value"]
- source: {fieldPath: data.cluster.smallstep.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.smallstep.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: StatefulSet, name: step-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-step-ca-config].env.[name=STEP_CA_DOMAIN].value"]
    options: {delimiter: '.', index: 1}
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=STEP_CA_DOMAIN].value"]
    options: {delimiter: '.', index: 1}
