apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smallstep
resources:
- ../settings
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- bootstrap.yaml
- certificates.yaml
- refresh-kube-config.yaml
- kube-apiserver-client-ca.yaml
- issuer.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/ca.json
  name: step-ca-config
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - config/templates/kube-apiserver-client-cert.tpl
  name: step-ca-templates
  options:
    labels:
      app.kubernetes.io/name: smallstep
- files:
  - ca.json=config/kube-apiserver-client-ca.json
  name: kube-apiserver-client-ca-config
  options:
    labels:
      app.kubernetes.io/name: smallstep
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.cluster.smallstep.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.smallstep.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
- source: {fieldPath: data.machines.k8sMaster.hostname, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job, name: bootstrap}
    fieldPaths: [spec.template.spec.nodeSelector.kubernetes\.io/hostname]
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: [spec.template.spec.nodeSelector.kubernetes\.io/hostname]
  - select: {group: batch, kind: CronJob, name: refresh-kube-config}
    fieldPaths: [spec.jobTemplate.spec.template.spec.nodeSelector.kubernetes\.io/hostname]
- source: {fieldPath: data.nfsShares.homeCluster.addr, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job}
    fieldPaths: ["spec.template.spec.volumes.[name=home-cluster].nfs.server"]
  - select: {group: batch, kind: CronJob}
    fieldPaths: ["spec.jobTemplate.spec.template.spec.volumes.[name=home-cluster].nfs.server"]
  - select: {group: apps, kind: StatefulSet}
    fieldPaths: ["spec.template.spec.volumes.[name=home-cluster].nfs.server"]
- source: {fieldPath: data.nfsShares.homeCluster.path, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job}
    fieldPaths: ["spec.template.spec.volumes.[name=home-cluster].nfs.path"]
  - select: {group: batch, kind: CronJob}
    fieldPaths: ["spec.jobTemplate.spec.template.spec.volumes.[name=home-cluster].nfs.path"]
  - select: {group: apps, kind: StatefulSet}
    fieldPaths: ["spec.template.spec.volumes.[name=home-cluster].nfs.path"]
