version: 0.1
log:
  accesslog:
    disabled: true
  level: info
  formatter: json
http:
  addr: :5000
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
  redirect:
    disable: false
validation:
  disabled: true
compatibility:
  schema1:
    enabled: false
auth:
  token:
    service: Docker registry
    issuer: Docker registry auth server
    autoredirect: false
    rootcertbundle: /etc/docker/auth/jwt.crt
redis:
  addr: redis.redis:6379
  db: 0
