apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- ../cluster-vars
- https://github.com/traefik/traefik-helm-chart.git//traefik/crds?ref=v27.0.2
- namespace.yaml
- traefik-deployment.yaml
- networkpolicy.yaml
- dashboard-ingress.yaml
- Kptfile
- resourcegroup.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata: {name: cluster-vars, annotations: {config.kubernetes.io/local-config: "true"}}
configMapGenerator:
- files:
  - config/file-provider.yaml
  - config/traefik.yaml
  name: traefik
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.DOMAIN, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [spec.tls.0.hosts.0]
    options:
      delimiter: .
      index: 1
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [spec.rules.0.host]
    options:
      delimiter: .
      index: 1
- source: {fieldPath: data.ACME_PROVIDER, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [metadata.annotations.cert-manager\.io/cluster-issuer]
