apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- ../settings
- https://github.com/traefik/traefik-helm-chart.git//traefik/crds?ref=v27.0.2
- namespace.yaml
- traefik-deployment.yaml
- networkpolicy.yaml
- dashboard-ingress.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/file-provider.yaml
  - config/traefik.yaml
  name: traefik
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [spec.tls.0.hosts.0]
    options: {delimiter: ., index: 1}
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [spec.rules.0.host]
    options: {delimiter: ., index: 1}
- source: {fieldPath: data.cluster.acmeProvider, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [metadata.annotations.cert-manager\.io/cluster-issuer]
- source: {fieldPath: data.cluster.traefik.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: traefik-frontend}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.traefik.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: traefik-frontend}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
