apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coredns
resources:
- ../cluster-vars
- coredns.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/Corefile
  name: coredns-config
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.DNS_SVC_IPV4, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.DNS_SVC_IPV6, kind: ConfigMap, name: cluster-vars}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
