apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- ../settings
- service.yaml
- networkpolicy.yaml
- Kptfile
- resourcegroup.yaml
replacements:
- source: {fieldPath: data.cluster.coredns.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.coredns.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
