apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coredns
resources:
- ../settings
- coredns.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/Corefile
  name: coredns-config
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.cluster.coredns.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.coredns.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: coredns}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=DOMAIN].value"]
- source: {fieldPath: data.cluster.wanIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=WAN_IPV4].value"]
- source: {fieldPath: data.machines.k8sMaster.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=K8SMASTER_IPV4].value"]
- source: {fieldPath: data.machines.k8sMaster.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=K8SMASTER_IPV6].value"]
