apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coredns
resources:
- ../cluster-vars
- coredns.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cluster-vars
      annotations:
        config.kubernetes.io/local-config: "true"
configMapGenerator:
- files:
  - config/Corefile
  name: coredns-config
replacements:
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.DNS_SVC_IPV4
  targets:
  - select:
      kind: Service
      name: coredns
    fieldPaths:
    - metadata.annotations.io\.cilium/lb-ipam-ips
    options:
      delimiter: ','
      index: 0
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.DNS_SVC_IPV6
  targets:
  - select:
      kind: Service
      name: coredns
    fieldPaths:
    - metadata.annotations.io\.cilium/lb-ipam-ips
    options:
      delimiter: ','
      index: 1
