apiVersion: kpt.dev/v1alpha1
kind: ResourceGroup
metadata:
  name: inventory-81838016
  namespace: kube-system
  labels:
    cli-utils.sigs.k8s.io/inventory-id: 50a6ad0492cb2c708b72de9e432622a0dcded78b-1712002891069871015
