apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: step-ca
resources:
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- bootstrap.yaml
- certificates.yaml
- issuer.yaml
- cluster-vars.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/bootstrap.sh
  name: step-ca-bootstrap
  options:
    labels:
      app.kubernetes.io/name: step-ca
- files:
  - config/setup-config.sh
  name: step-ca-setup-config
  options:
    labels:
      app.kubernetes.io/name: step-ca
- files:
  - config/ca.json
  name: step-ca-config
  options:
    labels:
      app.kubernetes.io/name: step-ca
- files: []
  name: step-ca-templates
  options:
    labels:
      app.kubernetes.io/name: step-ca
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.CLUSTER_NAME
  targets:
  - select:
      group: batch
      kind: Job
      name: step-ca-bootstrap
    fieldPaths:
    - spec.template.spec.containers.[name=step-ca-bootstrap].env.[name=CLUSTER_NAME].value
