apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- ../settings
- https://github.com/traefik/traefik-helm-chart.git//traefik/crds?ref=v27.0.2
- namespace.yaml
- traefik-deployment.yaml
- networkpolicy.yaml
- dashboard-ingress.yaml
- Kptfile
- resourcegroup.yaml
replacements:
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [spec.tls.0.hosts.0]
    options: {delimiter: ., index: 1}
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [spec.rules.0.host]
    options: {delimiter: ., index: 1}
- source: {fieldPath: data.cluster.acmeProvider.group, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-group]
- source: {fieldPath: data.cluster.acmeProvider.kind, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer-kind]
- source: {fieldPath: data.cluster.acmeProvider.issuer, kind: ConfigMap, name: settings}
  targets:
  - select: {group: networking.k8s.io, kind: Ingress, name: traefik-dashboard}
    fieldPaths: [metadata.annotations.cert-manager\.io/issuer]
- source: {fieldPath: data.cluster.traefik.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: traefik-frontend}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.traefik.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: traefik-frontend}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.nfsShares.homeCluster.addr, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps}
    fieldPaths: ["spec.template.spec.volumes.[name=home-cluster].nfs.server"]
- source: {fieldPath: data.nfsShares.homeCluster.path, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps}
    fieldPaths: ["spec.template.spec.volumes.[name=home-cluster].nfs.path"]
