---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boot-server
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boot-server
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
rules:
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: boot-server
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: boot-server
subjects:
- kind: ServiceAccount
  name: boot-server
---
apiVersion: v1
kind: Service
metadata:
  name: boot-server
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
  ports:
  - name: http
    port: 8020
    targetPort: http
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: disk-encryption-key
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
spec:
  fields:
  - fieldName: password
    encoding: base64url
    length: "32"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boot-server
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: boot-server
spec:
  serviceName: boot-server
  selector:
    matchLabels:
      app.kubernetes.io/name: node
      app.kubernetes.io/component: boot-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node
        app.kubernetes.io/component: boot-server
    spec:
      serviceAccountName: boot-server
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.27-alpine-slim
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: boot-assets
          containerPort: 8020
          hostPort: 8020
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: images
          mountPath: /var/www/images
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
      - name: registry
        image: cluster.local/registry:latest
        imagePullPolicy: Never
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: api
          containerPort: 8021
        volumeMounts:
        - name: scripts
          mountPath: /registry/registry.py
          subPath: registry.py
        - name: k3s-token
          mountPath: /secrets/k3s-token
          readOnly: true
        - name: registry
          mountPath: /data
        - name: registry-tmp
          mountPath: /tmp
      - name: tftpd
        image: cluster.local/tftpd:latest
        imagePullPolicy: Never
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
            add:
            - NET_BIND_SERVICE
            - NET_ADMIN
            - NET_RAW
            - SETUID
            - SETGID
            - SYS_CHROOT
            - SIGNAL
            - CAP_KILL
        env:
        # Used to select which interface tcpdump should filter for
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: tftp
          containerPort: 69
          hostPort: 69
        volumeMounts:
        - name: scripts
          mountPath: /tftpd.sh
          subPath: tftpd.sh
        - name: config
          mountPath: /config/map-file
          subPath: tftpd-map-file
        - name: images
          mountPath: /tftp/images
          readOnly: true
      - name: dhcp-proxy
        image: cluster.local/dhcp-proxy:latest
        imagePullPolicy: Never
        args:
        - $(HOST_IP)
        - $(TFTPD_ADDR)
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
            add:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - NET_RAW
            - SETGID
            - SETUID
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TFTPD_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: dhcp
          containerPort: 67
          hostPort: 67
        - name: dhcp-proxy
          containerPort: 4011
          hostPort: 4011
        volumeMounts:
        - name: scripts
          mountPath: /dhcp-proxy/dhcp-proxy.py
          subPath: dhcp-proxy.py
        - name: config
          mountPath: /dhcp-proxy/boot-map.yaml
          subPath: boot-map.yaml
      volumes:
      - name: config
        configMap:
          name: boot-server-config
      - name: scripts
        configMap:
          name: boot-server-scripts
          defaultMode: 0755
      - name: images
        persistentVolumeClaim:
          claimName: images
      - name: k3s-token
        hostPath:
          path: /var/lib/rancher/k3s/server/token
          type: File
      - name: disk-encryption-key
        secret:
          secretName: disk-encryption-key
      - name: nginx-cache
        emptyDir: {}
      - name: registry-tmp
        emptyDir: {}
      - name: dnsmasq-leases
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: registry
      labels:
        app.kubernetes.io/name: node
        app.kubernetes.io/component: boot-server
    spec:
      storageClassName: longhorn
      accessModes: [ReadWriteOnce]
      resources: {requests: {storage: 1Mi}}
