---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: images
spec:
  storageClassName: longhorn-rwx
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 10Gi}}
