apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node
resources:
- ../settings/replacements
- ../common-context
- containers/create-boot-image
- containers/dhcp-proxy
- containers/registry
- containers/tftpd
- bootstrap
- admin-pubkey.yaml
- images.yaml
- boot-server.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/boot-map.yaml
  - config/tftpd-map-file
  name: boot-server-config
- files:
  - scripts/dhcp-proxy.py
  - scripts/tftpd.sh
  - scripts/registry.py
  name: boot-server-scripts
replacements:
- source: {fieldPath: data.cluster.adminPubkey, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: ConfigMap, name: admin-pubkey}
    fieldPaths: [data.admin\.pub]
