apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node
resources:
- ../settings/replacements
- ../common-context
- containers/create-boot-image
- containers/dhcp-proxy
- containers/safeboot-attest
- containers/tftpd
- bootstrap
- images.yaml
- boot-server.yaml
- secureboot.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/boot-map.yaml.conf
  - config/nginx.conf
  - config/tftpd-map-file
  name: boot-server-config
- files:
  - scripts/dhcp-proxy.py
  - scripts/tftpd.sh
  - scripts/safeboot-attest/attest-server.py
  - scripts/safeboot-attest/attest-verify
  name: boot-server-scripts
