apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node
resources:
- ../settings/replacements
- ../common-context
- containers/create-boot-image
- containers/boot-server
- bootstrap
- admin-pubkey.yaml
- images.yaml
- boot-server.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - config/boot-map.yaml
  name: boot-server-config
- files:
  - scripts/boot-server.sh
  - scripts/boot-server/__init__.py
  - scripts/boot-server/__main__.py
  - scripts/boot-server/dhcp_proxy.py
  - scripts/boot-server/tftpd.py
  - scripts/boot-server/registry.py
  name: boot-server-scripts
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source: {fieldPath: data.cluster.adminPubkey, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: ConfigMap, name: admin-pubkey}
    fieldPaths: [data.admin\.pub]
