apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smallstep
resources:
- ../cluster-settings
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- bootstrap.yaml
- step-ca.yaml
- kube-apiserver-client-ca.yaml
- issuer.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - scripts/bootstrap.sh
  - scripts/setup-kube-apiserver-client-ca-config.sh
  - scripts/setup-step-ca-config.sh
  name: scripts
- files:
  - config/kube-apiserver-client-ca.json
  name: kube-apiserver-client-ca-config
- files:
  - config/templates/admin.tpl
  - config/templates/kube-apiserver-client-cert-renewal.tpl
  name: kube-apiserver-client-ca-templates
- files:
  - config/ca.json
  - config/kube-apiserver-client-ca.json
  name: ca-config
- files: []
  name: ca-templates
replacements:
- source: {fieldPath: data.domain, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.coredns\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.coredns\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: StatefulSet, name: step-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-step-ca-config].env.[name=CLUSTER_DOMAIN].value"]
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=CLUSTER_DOMAIN].value"]
- source: {fieldPath: data.admin.ssh-key, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=CLUSTER_ADMIN_SSH_KEY].value"]
