apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smallstep
resources:
- ../settings/replacements
- ../common-context
- containers/step-ca-bootstrap
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- bootstrap.yaml
- certificates.yaml
- kube-apiserver-client-ca.yaml
- issuer.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - scripts/bootstrap.sh
  - scripts/setup-kube-apiserver-client-ca-config.sh
  - scripts/setup-step-ca-config.sh
  name: scripts
- files:
  - config/ca.json
  - config/kube-apiserver-client-ca.json
  name: config
- files:
  - config/templates/admin.tpl
  - config/templates/kube-apiserver-client-cert-renewal.tpl
  name: templates
replacements:
- source: {fieldPath: data.cluster.smallstep.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
  - select: {group: apps, kind: StatefulSet, name: step-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-step-ca-config].env.[name=CLUSTER_SMALLSTEP_FIXEDIPV4].value"]
- source: {fieldPath: data.cluster.smallstep.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
  - select: {group: apps, kind: StatefulSet, name: step-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-step-ca-config].env.[name=CLUSTER_SMALLSTEP_FIXEDIPV6].value"]
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=CLUSTER_KUBEAPISERVERCLIENTCA_FIXEDIPV4].value"]
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=CLUSTER_KUBEAPISERVERCLIENTCA_FIXEDIPV6].value"]
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: StatefulSet, name: step-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-step-ca-config].env.[name=CLUSTER_DOMAIN].value"]
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=CLUSTER_DOMAIN].value"]
- source: {fieldPath: data.cluster.adminPubkey, kind: ConfigMap, name: settings}
  targets:
  - select: {group: apps, kind: StatefulSet, name: kube-apiserver-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-apiserver-client-ca-config].env.[name=CLUSTER_ADMINPUBKEY].value"]
