apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smallstep
resources:
- ../settings/replacements
- ../common-context
- containers/step-ca-bootstrap
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- bootstrap.yaml
- certificates.yaml
- refresh-kube-config.yaml
- kube-apiserver-client-ca.yaml
- issuer.yaml
- namespace.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - scripts/bootstrap.sh
  - scripts/create-kube-config.sh
  - scripts/setup-kube-apiserver-client-ca-config.sh
  - scripts/setup-step-ca-config.sh
  name: scripts
- files:
  - config/ca.json
  - config/kube-apiserver-client-ca.json
  - config/templates/kube-apiserver-client-cert.tpl
  name: config
- files:
  - config/templates/kube-apiserver-client-cert.tpl
  name: templates
replacements:
- source: {fieldPath: data.cluster.smallstep.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.smallstep.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv4, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 0}
- source: {fieldPath: data.cluster.kubeAPIServerClientCA.fixedIPv6, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.io\.cilium/lb-ipam-ips]
    options: {delimiter: ',', index: 1}
- source: {fieldPath: data.cluster.domain, kind: ConfigMap, name: settings}
  targets:
  - select: {kind: Service, name: step-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {kind: Service, name: kube-apiserver-client-ca-external}
    fieldPaths: [metadata.annotations.external-dns\.alpha\.kubernetes\.io/hostname]
    options: {delimiter: '.', index: 1}
- source: {fieldPath: data.admin.uid, kind: ConfigMap, name: settings}
  targets:
  - select: {group: batch, kind: Job, name: bootstrap}
    fieldPaths: ["spec.template.spec.containers.[name=bootstrap].env.[name=ADMIN_UID].value"]

  - select: {group: batch, kind: CronJob, name: refresh-kube-config}
    fieldPaths: ["spec.jobTemplate.spec.template.spec.containers.[name=refresh-kube-config].env.[name=ADMIN_UID].value"]
