apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-kube-config
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: refresh-kube-config
spec:
  schedule: "00 05 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: smallstep
            app.kubernetes.io/component: refresh-kube-config
            cluster.local/allow-internet-egress: "true"
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          restartPolicy: Never
          containers:
          - name: refresh-kube-config
            image: cluster.local/step-ca-bootstrap:latest
            imagePullPolicy: Never
            command: [/home/step/scripts/create-kube-config.sh]
            args: ['system:admin', 'system:masters']
            env:
            - name: ADMIN_UID
              value: admin.uid
            securityContext:
              readOnlyRootFilesystem: true
            volumeMounts:
            - name: scripts
              mountPath: /home/scripts
            - name: certs
              mountPath: /home/step/certs
            - name: kube-apiserver-client-ca-cert
              mountPath: /home/step/certs/kube_apiserver_client_ca.crt
              readOnly: true
            - name: kube-apiserver-client-ca-key
              mountPath: /home/step/certs/kube_apiserver_client_ca_key
              readOnly: true
            - name: persistent-certs
              mountPath: /home/step/persistent-certs
          volumes:
          - name: scripts
            configMap:
              name: scripts
              defaultMode: 0755
          - name: kube-apiserver-client-ca-cert
            hostPath:
              path: /var/lib/rancher/k3s/server/tls/client-ca.crt
              type: File
          - name: kube-apiserver-client-ca-key
            hostPath:
              path: /var/lib/rancher/k3s/server/tls/client-ca.key
              type: File
          - name: certs
            emptyDir:
              medium: Memory
          - name: persistent-certs
            persistentVolumeClaim:
              claimName: step-ca-certs
