apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../cluster-vars
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/rbac-csi-nfs.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/csi-nfs-driverinfo.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/csi-nfs-controller.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/csi-nfs-node.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/crd-csi-snapshot.yaml
- nas.yaml
- networkpolicies.yaml
- Kptfile
- resourcegroup.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cluster-vars
      annotations:
        config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.CLUSTER_NFS_SERVER_IP
  targets:
  - select:
      group: storage.k8s.io
      kind: StorageClass
      name: nas-nfs
    fieldPaths:
    - parameters.server
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.CLUSTER_NFS_SHARE
  targets:
  - select:
      group: storage.k8s.io
      kind: StorageClass
      name: nas-nfs
    fieldPaths:
    - parameters.share
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.CLUSTER_NFS_SUBDIR
  targets:
  - select:
      group: storage.k8s.io
      kind: StorageClass
      name: nas-nfs
    fieldPaths:
    - parameters.subDir
- source:
    kind: ConfigMap
    name: cluster-vars
    fieldPath: data.CLUSTER_NFS_SERVER_IP_CIDR
  targets:
  - select:
      group: networking.k8s.io
      kind: NetworkPolicy
      name: csi-nfs
    fieldPaths:
    - spec.ingress.0.from.0.ipBlock.cidr
  - select:
      group: networking.k8s.io
      kind: NetworkPolicy
      name: csi-nfs
    fieldPaths:
    - spec.egress.0.to.0.ipBlock.cidr
