apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../settings
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/rbac-csi-nfs.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/csi-nfs-driverinfo.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/csi-nfs-controller.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/csi-nfs-node.yaml
- https://github.com/kubernetes-csi/csi-driver-nfs/raw/master/deploy/v4.6.0/crd-csi-snapshot.yaml
- nas.yaml
- Kptfile
- resourcegroup.yaml
replacements:
- source: {fieldPath: data.nfsShares.homeCluster.addr, kind: ConfigMap, name: settings}
  targets:
  - select: {group: storage.k8s.io, kind: StorageClass, name: nas-nfs-images}
    fieldPaths: [parameters.server]
- source: {fieldPath: data.nfsShares.homeCluster.path, kind: ConfigMap, name: settings}
  targets:
  - select: {group: storage.k8s.io, kind: StorageClass, name: nas-nfs-images}
    fieldPaths: [parameters.share]
- source: {fieldPath: data.nfsShares.workloads.addr, kind: ConfigMap, name: settings}
  targets:
  - select: {group: storage.k8s.io, kind: StorageClass, name: nas-nfs-workloads}
    fieldPaths: [parameters.server]
- source: {fieldPath: data.nfsShares.workloads.path, kind: ConfigMap, name: settings}
  targets:
  - select: {group: storage.k8s.io, kind: StorageClass, name: nas-nfs-workloads}
    fieldPaths: [parameters.share]
