name: Build coredns container with k8s_gateway

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
    paths:
    - .github/workflows/build-coredns.yaml
    - .github/assets/coredns.Dockerfile

env:
  COREDNS_VERSION: '1.12.0'
  GO_VERSION: '1.23.4'
  K8SGW_VERSION: '0.4.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .github/assets
        file: .github/assets/coredns.Dockerfile
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
          COREDNS_VERSION=${{ env.COREDNS_VERSION }}
          K8SGW_VERSION=${{ env.K8SGW_VERSION }}
        tags: ghcr.io/andsens/phxc-coredns:${{ env.COREDNS_VERSION }}
