name: Upload the rpi-otp.yaml schema to gist.github.com

on:
  push:
    branches: [ 'main' ]
    paths:
    - .github/workflows/update-rpi-otp-schema.yaml
    - lib/schemas/rpi-otp.yaml

jobs:
  update-rpi-otp-schema:
    name: Update the gist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: repo
    - name: Convert rpi-otp.yaml to JSON
      run: yq -o=json . repo/lib/schemas/rpi-otp.yaml >rpi-otp.json
    - name: Deploy to gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: ${{ vars.CONFIG_SCHEMAS_GIST_ID }}
        file_path: rpi-otp.json
        file_type: application/schema+json
