name: Upload the node.yaml schema to gist.github.com

on:
  push:
    branches: [ 'main' ]
    paths:
    - .github/workflows/update-node-schema.yaml
    - lib/schemas/node.yaml

jobs:
  update-node-config-schema:
    name: Update the gist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: repo
    - name: Convert node.yaml to JSON
      run: yq -o=json . repo/lib/schemas/node.yaml >node.json
    - name: Deploy to gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: ${{ vars.CONFIG_SCHEMAS_GIST_ID }}
        file_path: node.json
        file_type: application/schema+json
