name: Upload the cli.json schema to gist.github.com

on:
  push:
    branches: [ 'main' ]
    paths:
    - .github/workflows/update-cli-schema.yaml
    - cli/lib/schemas/cli.json

jobs:
  update-cli-config-schema:
    name: Update the gist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: repo
    - name: Deploy to gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: ${{ vars.CONFIG_SCHEMAS_GIST_ID }}
        file_path: repo/cli/lib/schemas/cli.json
        file_type: application/schema+json
