name: Upload the cluster.yaml schema to gist.github.com

on:
  push:
    branches: [ 'master' ]
    paths:
    - .github/workflows/update-schema.yaml
    - workloads/node/bootstrap/assets/usr/local/lib/phoenix-cluster/cluster.schema.yaml

jobs:
  update-node-config-schema:
    name: Update the gist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: repo
    - name: Convert cluster.schema.yaml to JSON
      run: yq -o=json . repo/workloads/node/bootstrap/assets/usr/local/lib/phoenix-cluster/cluster.schema.yaml >cluster.schema.json
    - name: Deploy to gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: ${{ vars.CONFIG_SCHEMAS_GIST_ID }}
        file_path: cluster.schema.json
        file_type: application/schema+json
